# Generated by Django 4.2.6 on 2023-11-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvresultAbaAt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(blank=True, db_column='Uniprot_ID', max_length=50, null=True)),
                ('protein_names', models.CharField(blank=True, db_column='Protein_names', max_length=512, null=True)),
                ('gene_names', models.CharField(blank=True, db_column='Gene_Names', max_length=128, null=True)),
                ('organism', models.CharField(blank=True, db_column='Organism', max_length=50, null=True)),
                ('pdb', models.CharField(blank=True, db_column='PDB', max_length=256, null=True)),
                ('pocket_id', models.CharField(blank=True, db_column='Pocket_ID', max_length=50, null=True)),
                ('binding_affinity', models.FloatField(blank=True, db_column='Binding_affinity', null=True)),
            ],
            options={
                'db_table': 'InvResult_ABA_At',
            },
        ),
    ]
