# Generated by Django 4.2.6 on 2024-06-05 04:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvvinaTask',
            fields=[
                ('jobid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('smiles_input', models.CharField(max_length=1024)),
                ('protein_list', models.TextField()),
                ('plant', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InvvinaTaskReuslt',
            fields=[
                ('smile', models.CharField(max_length=1024)),
                ('plant', models.CharField(max_length=100)),
                ('pocket_id', models.CharField(db_column='Pocket_ID', max_length=50, primary_key=True, serialize=False)),
                ('uniprot_id', models.CharField(blank=True, db_column='Uniprot_ID', max_length=50, null=True)),
                ('afdb_id', models.CharField(blank=True, db_column='AFDB_ID', max_length=50, null=True)),
                ('binding_affinity', models.FloatField(blank=True, db_column='Binding_affinity', null=True)),
                ('entry', models.CharField(blank=True, db_column='Entry', max_length=50, null=True)),
                ('pdb', models.CharField(blank=True, db_column='PDB', max_length=256, null=True)),
                ('string', models.CharField(blank=True, db_column='STRING', max_length=50, null=True)),
                ('bindingdb', models.CharField(blank=True, db_column='BindingDB', max_length=50, null=True)),
                ('orthodb', models.CharField(blank=True, db_column='OrthoDB', max_length=50, null=True)),
                ('expressionatlas', models.CharField(blank=True, db_column='ExpressionAtlas', max_length=50, null=True)),
                ('gene_names', models.CharField(blank=True, db_column='Gene_Names', max_length=512, null=True)),
                ('protein_names', models.CharField(blank=True, db_column='Protein_names', max_length=512, null=True)),
                ('organism', models.CharField(blank=True, db_column='Organism', max_length=50, null=True)),
                ('subcellular_location', models.CharField(blank=True, db_column='Subcellular_location', max_length=2048, null=True)),
                ('function_description', models.CharField(blank=True, db_column='Function_description', max_length=8192, null=True)),
                ('doi_id', models.CharField(blank=True, db_column='DOI_ID', max_length=2048, null=True)),
                ('ligand_path', models.CharField(blank=True, db_column='Ligand_path', max_length=128, null=True)),
                ('receptor_path', models.CharField(blank=True, db_column='Receptor_path', max_length=128, null=True)),
                ('complex_path', models.CharField(blank=True, db_column='Complex_Path', max_length=128, null=True)),
            ],
        ),
    ]
